<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="14" passed="13" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-05-02T11:07:02 IST" name="Default suite" finished-at="2023-05-02T11:21:24 IST" duration-ms="862261">
    <groups>
    </groups>
    <test started-at="2023-05-02T11:07:02 IST" name="Default test" finished-at="2023-05-02T11:21:24 IST" duration-ms="862261">
      <class name="testcases.RepairTestCases">
        <test-method is-config="true" signature="login()[pri:0, instance:testcases.RepairTestCases@1e6a3214]" started-at="2023-05-02T11:07:02 IST" name="login" finished-at="2023-05-02T11:07:13 IST" duration-ms="11057" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="testCase1()[pri:1, instance:testcases.RepairTestCases@1e6a3214]" started-at="2023-05-02T11:07:13 IST" name="testCase1" finished-at="2023-05-02T11:07:47 IST" duration-ms="33226" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase1 -->
        <test-method signature="testCase2()[pri:2, instance:testcases.RepairTestCases@1e6a3214]" started-at="2023-05-02T11:07:47 IST" name="testCase2" finished-at="2023-05-02T11:08:36 IST" duration-ms="49378" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase2 -->
        <test-method signature="testCase3()[pri:3, instance:testcases.RepairTestCases@1e6a3214]" started-at="2023-05-02T11:08:36 IST" name="testCase3" finished-at="2023-05-02T11:09:16 IST" duration-ms="39827" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at testcases.RepairTestCases.testCase3(RepairTestCases.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase3 -->
        <test-method signature="testCase4()[pri:4, instance:testcases.RepairTestCases@1e6a3214]" started-at="2023-05-02T11:09:16 IST" name="testCase4" finished-at="2023-05-02T11:10:08 IST" duration-ms="51874" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase4 -->
        <test-method signature="testCase5()[pri:5, instance:testcases.RepairTestCases@1e6a3214]" started-at="2023-05-02T11:10:08 IST" name="testCase5" finished-at="2023-05-02T11:11:03 IST" duration-ms="55888" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase5 -->
        <test-method signature="testCase6()[pri:6, instance:testcases.RepairTestCases@1e6a3214]" started-at="2023-05-02T11:11:04 IST" name="testCase6" finished-at="2023-05-02T11:12:04 IST" duration-ms="60248" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase6 -->
        <test-method signature="testCase7()[pri:7, instance:testcases.RepairTestCases@1e6a3214]" started-at="2023-05-02T11:12:04 IST" name="testCase7" finished-at="2023-05-02T11:13:10 IST" duration-ms="65755" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase7 -->
        <test-method signature="testCase8()[pri:8, instance:testcases.RepairTestCases@1e6a3214]" started-at="2023-05-02T11:13:10 IST" name="testCase8" finished-at="2023-05-02T11:14:18 IST" duration-ms="68554" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase8 -->
        <test-method signature="testCase9()[pri:9, instance:testcases.RepairTestCases@1e6a3214]" started-at="2023-05-02T11:14:18 IST" name="testCase9" finished-at="2023-05-02T11:16:04 IST" duration-ms="106350" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase9 -->
        <test-method signature="testCase10()[pri:10, instance:testcases.RepairTestCases@1e6a3214]" started-at="2023-05-02T11:16:04 IST" name="testCase10" finished-at="2023-05-02T11:17:55 IST" duration-ms="110497" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase10 -->
        <test-method signature="testCase11()[pri:11, instance:testcases.RepairTestCases@1e6a3214]" started-at="2023-05-02T11:17:55 IST" name="testCase11" finished-at="2023-05-02T11:19:49 IST" duration-ms="114200" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase11 -->
        <test-method signature="testCase12()[pri:12, instance:testcases.RepairTestCases@1e6a3214]" started-at="2023-05-02T11:19:49 IST" name="testCase12" finished-at="2023-05-02T11:20:30 IST" duration-ms="40993" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase12 -->
        <test-method signature="testCase13()[pri:13, instance:testcases.RepairTestCases@1e6a3214]" started-at="2023-05-02T11:20:30 IST" name="testCase13" finished-at="2023-05-02T11:20:55 IST" duration-ms="25116" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase13 -->
        <test-method signature="testCase14()[pri:14, instance:testcases.RepairTestCases@1e6a3214]" started-at="2023-05-02T11:20:55 IST" name="testCase14" finished-at="2023-05-02T11:21:24 IST" duration-ms="29205" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase14 -->
        <test-method is-config="true" signature="logout()[pri:0, instance:testcases.RepairTestCases@1e6a3214]" started-at="2023-05-02T11:21:24 IST" name="logout" finished-at="2023-05-02T11:21:24 IST" duration-ms="8" status="FAIL">
          <exception class="org.openqa.selenium.NoSuchSessionException">
            <message>
              <![CDATA[invalid session id
Build info: version: '4.8.0', revision: '267030adea'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-71-generic', java.version: '17.0.5'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [409d5dba0430b71036d98f799bf5a7ca, findElement {using=xpath, value=//*[@class='down-arrow']}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 106.0.5249.119, chrome: {chromedriverVersion: 106.0.5249.61 (511755355844..., userDataDir: /tmp/.com.google.Chrome.ixaBKc}, goog:chromeOptions: {debuggerAddress: localhost:39333}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: LINUX, proxy: Proxy(), se:cdp: ws://localhost:39333/devtoo..., se:cdpVersion: 106.0.5249.119, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 409d5dba0430b71036d98f799bf5a7ca]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.NoSuchSessionException: invalid session id
Build info: version: '4.8.0', revision: '267030adea'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-71-generic', java.version: '17.0.5'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [409d5dba0430b71036d98f799bf5a7ca, findElement {using=xpath, value=//*[@class='down-arrow']}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 106.0.5249.119, chrome: {chromedriverVersion: 106.0.5249.61 (511755355844..., userDataDir: /tmp/.com.google.Chrome.ixaBKc}, goog:chromeOptions: {debuggerAddress: localhost:39333}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: LINUX, proxy: Proxy(), se:cdp: ws://localhost:39333/devtoo..., se:cdpVersion: 106.0.5249.119, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 409d5dba0430b71036d98f799bf5a7ca
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:162)
at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:60)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:352)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:344)
at commonUtils.App.logout(App.java:47)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:644)
at org.testng.TestRunner.afterRun(TestRunner.java:914)
at org.testng.TestRunner.run(TestRunner.java:605)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.NoSuchSessionException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
      </class> <!-- testcases.RepairTestCases -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
